spring:
  flyway:
    enabled: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-testing.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;
    username: sa
    password:
    driverClassName: org.h2.Driver