spring:
  flyway:
    locations: classpath:db/migration,classpath:db/datatest
    schemas: restaurant_schema
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: ${db_user}
    password: ${db_password}
    driverClassName: org.postgresql.Driver
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 20
      minimum-idle: 10

## Useful properties     
#

#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update

#spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=src/main/resources/sql/ddl.sql

