spring:
  flyway:
    locations: classpath:db/migration,classpath:db/datatest
    schemas: restaurant_schema
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: ${db_user}
    password: ${db_password}
    driverClassName: org.postgresql.Driver
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 20
      minimum-idle: 10
